// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

export type SamplingSettingsEffectiveNotification = { threadId: string, rootTurnId: string, samplingRequestId: string, modelProviderId: string, model: string, reasoningEffort: ReasoningEffort | null, attempt: bigint, };
